version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    hostname: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/:/mosquitto/
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  
  binancebot:
    build: 
      context: ./binance
      dockerfile: Dockerfile      
    hostname: binancebot
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  slackbot:
    build:
      context: ./slack
      dockerfile: Dockerfile
    hostname: slackbot
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"
