version: "3.9"
services:
  mosquitto:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  binancebot:
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./binance:/app/binance/
      - ./utils/:/app/binance/utils/
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"
    command: python3 -u ./binance/binancebot.py

  slackbot:
    restart: always
    ports:
      - 5001:5001
    volumes:
      - ./slack:/app/slack/
      - ./utils/:/app/slack/utils/
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"
    command: python3 -u ./slack/slackbot.py
