version: "3.9"
services:
  binancebot:
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./binance:/app/binance/
      - ./utils/:/app/binance/utils/
    command: python3 -u ./binance/binancebot.py

  slackbot:
    restart: always
    ports:
     - 5001:5001
    volumes:
      - ./slack:/app/slack/
      - ./utils/:/app/slack/utils/
    command: python3 -u ./slack/slackbot.py
    