version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/:/mosquitto/

  binancebot:
    build:
      context: ./binance
      dockerfile: Dockerfile
    container_name: binancebot
    hostname: binancebot
    ports:
      - 5002:5002
    volumes:
      - ./binance:/app/binance/
      - ./utils/:/app/binance/utils/
    env_file:
      - .env

  slackbot:
    build:
      context: ./slack
      dockerfile: Dockerfile
    container_name: slackbot
    hostname: slackbot
    ports:
      - 5001:5001
    volumes:
      - ./slack:/app/slack/
      - ./utils/:/app/slack/utils/
    env_file:
      - .env
