version: "3.9"
services:
  mosquitto:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  binancebot:
    image: binancebot:${RELEASE_VERSION}
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  slackbot:
    image: slackbot:${RELEASE_VERSION}
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"
