version: "3.9"
services:
  binancebot:
    ports:
      - 5000:5000
    volumes:
      - ./binance:/app/binance/
      - ./utils/:/app/binance/utils/
    command: tail -f /dev/null

  slackbot:
    ports:
     - 5001:5001
    volumes:
      - ./slack:/app/slack/
      - ./utils/:/app/slack/utils/
    command: tail -f /dev/null
