version: "3.9"
services:
  mosquitto:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  binancebot:
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"
    command: python3 -u ./main.py

  slackbot:
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"
    command: python3 -u ./main.py
