version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/:/mosquitto/
  
  binancebot:
    build: 
      context: ./binance
      dockerfile: Dockerfile      
    hostname: binancebot
    env_file:
      - .env

  slackbot:
    build:
      context: ./slack
      dockerfile: Dockerfile
    hostname: slackbot
    env_file:
      - .env

